services:
  - type: web
    name: twitter-clone
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn twitter.wsgi:application
    envVars:
      - key: DEBUG
        value: "True"
      - key: SECRET_KEY
        generateValue: true
